import Head from 'next/head';
import Footer from '../components/Footer';
// import styles from '../styles/Home.module.css';
import Header from '../components/Header';
import Button from '../components/UI/Button';
import Image from 'next/image';
import { DefaultSeo } from 'next-seo';
import Iframe from 'react-iframe';
import { useState } from 'react';
import axios from './../helper/AxiosService';
export default function Home() {
  const [name, setName] = useState('');
  const submitForm = async (e) => {
    e.preventDefault();
    console.log(e);
    const formData = new FormData();
    formData.append('entry.506450849', name);
    const res = await axios.post(
      'https://docs.google.com/forms/u/0/d/e/1FAIpQLSevkiBjcpkKBwUzWlop904kB8-asiQiHl3eQLlHx90gcCSFOw/formResponse',
      formData,
    );
    if (res.status === 200) {
      console.log(res);
    } else {
      console.log('error');
    }
  };
  return (
    <div>
      <DefaultSeo
        openGraph={{
          type: 'website',
          locale: 'en_IE',
          url: 'https://truyenmai.com',
          site_name: 'Truyền Mai',
        }}
        description="Generated by create next app"
        title="Truyền Mai Blog"
        additionalLinkTags={[
          {
            rel: 'icon',
            href: '/image/logo192.png',
          },
          {
            rel: 'Truyen-Mai-icon',
            href: '/image/logo192.png',
            sizes: '76x76',
          },
          {
            rel: 'manifest',
            href: '/manifest.json',
          },
        ]}
      />
      <div className="p-0">
        <div
          className="col-md-12 mb-3"
          style={{ maxWidth: '100%', height: 300, backgroundColor: '#f9f9f9' }}
        >
          <h1 style={{ textAlign: 'center' }}>
            Welcome to <a href="https://nextjs.org">Blog.js!</a>
          </h1>
        </div>
      </div>

      <div className="wrapper" style={{ padding: '25px 100px', margin: 0 }}>
        <div className="row">
          <h2 style={{ textAlign: 'center' }}>Tell me your story</h2>
          <form onSubmit={submitForm}>
            <input
              type="text"
              style={{ border: '1px solid red' }}
              value={name}
              onChange={(e) => setName(e.target.value)}
            />
            <button type="submit">Submit</button>
          </form>
        </div>

        <div className="row">
          <div className="col-md-6">
            <h3>About me</h3>
            <p
              dangerouslySetInnerHTML={{
                __html: `Let's be honest and cut through the marketing fluff. You need a
                website that looks amazing and actually works. The bottom line,
                that's what I do. And if you want to learn more about working
                with me, connect with me today.`,
              }}
            ></p>
            <button className="btn">Learn More</button>
          </div>
          <div className="col-md-6">
            <div
              style={{
                width: '100%',
                height: 300,
                backgroundColor: '#f9f9f9',
              }}
            ></div>
          </div>
        </div>

        <div className="row">
          <h3>Our Project</h3>
          <div className="col-md-3 mb-3">
            <div
              style={{
                width: '100%',
                height: 200,
                backgroundColor: '#f9f9f9',
              }}
            ></div>
          </div>

          <div className="col-md-3 mb-3">
            <div
              style={{
                width: '100%',
                height: 200,
                backgroundColor: '#f9f9f9',
              }}
            ></div>
          </div>

          <div className="col-md-3 mb-3">
            <div
              style={{
                width: '100%',
                height: 200,
                backgroundColor: '#f9f9f9',
              }}
            ></div>
          </div>

          <div className="col-md-3 mb-3">
            <div
              style={{
                width: '100%',
                height: 200,
                backgroundColor: '#f9f9f9',
              }}
            ></div>
          </div>

          <div className="col-md-3 mb-3">
            <div
              style={{
                width: '100%',
                height: 200,
                backgroundColor: '#f9f9f9',
              }}
            ></div>
          </div>

          <div className="col-md-3 mb-3">
            <div
              style={{
                width: '100%',
                height: 200,
                backgroundColor: '#f9f9f9',
              }}
            ></div>
          </div>

          <div className="col-md-3 mb-3">
            <div
              style={{
                width: '100%',
                height: 200,
                backgroundColor: '#f9f9f9',
              }}
            ></div>
          </div>

          <div className="col-md-3 mb-3">
            <div
              style={{
                width: '100%',
                height: 200,
                backgroundColor: '#f9f9f9',
              }}
            ></div>
          </div>
        </div>
      </div>
    </div>
  );
}
